<a href="https://colab.research.google.com/github/Bertha-ding/20MA573-yuning-ding/blob/master/hw/hw8code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Compute CFD solution

$ h = \frac{1}{5}$ and $\epsilon = 10^{-10}$, below is Lh
$$ A = 
 \begin{bmatrix}
 1  &  0  &  0  &  0  &  0  & 0  \\
 -r &  s  & -r  &  0  &  0  & 0  \\
 0  & -r  & s   &  -r &  0  & 0  \\
 0  &  0  & -r  &  s  & -r  & 0   \\
 0  &  0  & 0   & -r  &  s  & -r  \\
 0  &  0  & 0   &  0  &  0  &  1 
\end{bmatrix}
$$

In [0]:
import numpy as np
from scipy.linalg import solve
e = 10**(-10)
interval_num = 5
r = e*(interval_num**2)
s = 2*r + 1
Rhf = np.zeros((interval_num+1))
Rhf[0] = 0
Rhf[-1] = 0
for i in range(interval_num):
  Rhf[i+1] = Rhf[i] + 1/interval_num
Lhuh=np.zeros((interval_num+1,interval_num+1))
Lhuh[0,0]=1
Lhuh[-1,-1]=1
for i in range(interval_num-1):
  Lhuh[i+1,i]=-r
  Lhuh[i+1,i+1]=s
  Lhuh[i+1,i+2]=-r
uh = solve(Lhuh,Rhf)

In [47]:
uh

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

# Compare CFD with FEM

In [0]:
e = 10**(-10)
interval_num = 9
r = e*(interval_num**2)
s = 2*r + 1
Rhf = np.zeros((interval_num+1))
Rhf[0] = 0
Rhf[-1] = 0
for i in range(interval_num):
  Rhf[i+1] = Rhf[i] + 1/interval_num
Lhuh=np.zeros((interval_num+1,interval_num+1))
Lhuh[0,0]=1
Lhuh[-1,-1]=1
for i in range(interval_num-1):
  Lhuh[i+1,i]=-r
  Lhuh[i+1,i+1]=s
  Lhuh[i+1,i+2]=-r
uh = solve(Lhuh,Rhf)

In [49]:
uh

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [0]:
diff_arr = np.zeros(10)
interval_num = 9
e = 10**(-10)
Rhf = np.zeros((interval_num+1))
Rhf[0] = 0
for i in range(interval_num):
  Rhf[i+1] = Rhf[i] + 1/(interval_num-1)
  x = Rhf[i]
  u = x - (np.exp((x - 1)/np.sqrt(e)) - np.exp(- (x+1)/np.sqrt(e))) / (1 - np.exp(- 2 / np.sqrt(e)))
  diff = np.abs(u - uh[i])
  diff_arr[i] = diff  

In [68]:
diff_arr

array([0.        , 0.01388889, 0.02777778, 0.04166667, 0.05555556,
       0.06944444, 0.08333333, 0.09722222, 0.88888889, 0.        ])