<a href="https://colab.research.google.com/github/Bertha-ding/20MA573-yuning-ding/blob/master/hw/hw9code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
def init_val(n):
  u=np.zeros([n+1,n+1])
  for i in range(n+1):
    for j in range(n+1):
      if i==0 or i ==n or j==0 or j==n:
        u[i,j] = (i/n-1/2)**2+(j/n-1/2)**2
      else:
        u[i,j] = 0
  return u

In [38]:
init_val(4)

array([[0.5   , 0.3125, 0.25  , 0.3125, 0.5   ],
       [0.3125, 0.    , 0.    , 0.    , 0.3125],
       [0.25  , 0.    , 0.    , 0.    , 0.25  ],
       [0.3125, 0.    , 0.    , 0.    , 0.3125],
       [0.5   , 0.3125, 0.25  , 0.3125, 0.5   ]])

In [0]:
def gamma(n):
  h = 1/n
  gamma = 2/(2 + h**2)

  return gamma

In [39]:
gamma(4)

0.9696969696969697

In [0]:
def lh(n):
  h = 1/n
  lh = np.zeros([n+1, n+1])
  for i in range(n+1):
    for j in range(n+1):
      if i == 0 or i == n or j == 0 or j == n:
        lh[i, j] = 0
      else:
        lh[i, j] = (h**2/2)*((i/n)**2+(j/n)**2 - i/n - j/n - 3/2)
  return lh

In [40]:
lh(4)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.05859375, -0.06054688, -0.05859375,  0.        ],
       [ 0.        , -0.06054688, -0.0625    , -0.06054688,  0.        ],
       [ 0.        , -0.05859375, -0.06054688, -0.05859375,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [0]:
def F(n, u):
  h = 1/n
  l= lh(n)
  v = np.zeros([n+1, n+1])
  for i in range(0, n+1):
    for j in range(0, n+1):
      if i == 0 or i == n or j == 0 or j == n:
        v[i, j] = u[i, j]
      else:
        v[i, j] = gamma(n) * l[i, j] + gamma(n) * (u[i+1, j] + u[i, j+1] + u[i, j-1] + u[i-1, j]) / 4
  
  return v


In [58]:
def VI(n, tolerance=0.0001):
  v = init_val(n)
  err = 0.1
  n_hat = 0
  if err>tolerance:
    n_hat +=1
    u = v
    v = F(n,u)
    err=np.max(np.abs(u-v))
  return [err,v]

print(VI(4, tolerance=0.0001))

[0.0946969696969697, array([[ 0.5       ,  0.3125    ,  0.25      ,  0.3125    ,  0.5       ],
       [ 0.3125    ,  0.09469697,  0.00189394,  0.09469697,  0.3125    ],
       [ 0.25      ,  0.00189394, -0.06060606,  0.00189394,  0.25      ],
       [ 0.3125    ,  0.09469697,  0.00189394,  0.09469697,  0.3125    ],
       [ 0.5       ,  0.3125    ,  0.25      ,  0.3125    ,  0.5       ]])]


In [66]:
def exact_val(n):
  exact_val = np.zeros([n+1, n+1])
  for i in range(0, n+1):
    for j in range(0, n+1):
      exact_val[i, j] = (i/n - 0.5)**2 + (j/n - 0.5)**2
  
  return exact_val

print("The exact value of the PDE is:")
print(exact_val(4))
print("The computed value of the PDE is:")
print(VI(4, tolerance=0.0001)[1])


The exact value of the PDE is:
[[0.5    0.3125 0.25   0.3125 0.5   ]
 [0.3125 0.125  0.0625 0.125  0.3125]
 [0.25   0.0625 0.     0.0625 0.25  ]
 [0.3125 0.125  0.0625 0.125  0.3125]
 [0.5    0.3125 0.25   0.3125 0.5   ]]
The computed value of the PDE is:
[[ 0.5         0.3125      0.25        0.3125      0.5       ]
 [ 0.3125      0.09469697  0.00189394  0.09469697  0.3125    ]
 [ 0.25        0.00189394 -0.06060606  0.00189394  0.25      ]
 [ 0.3125      0.09469697  0.00189394  0.09469697  0.3125    ]
 [ 0.5         0.3125      0.25        0.3125      0.5       ]]


for h = 2**(-i), i=2,3,4,5

In [76]:
for i in range(4):
  n = 2**(i+2)
  h =1/n
  err = np.max(np.abs(VI(n, tolerance=0.0001)[1]  - exact_val(n)))
  print(err)
  

0.06060606060606061
0.13953488372093023
0.28460038986354774
0.383601756954612
